server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
      eviction-interval-timer-in-ms: 4000
      enableSelfPreservation: false
      renewalPercentThreshold: 0.9


